networks:
  ev_network:
    driver: bridge
services:
  e-mobility-charging-stations-dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - ev_network
    ports:
      - 3030:3030
