name: 'Bug report'
title: '[BUG] '
labels: ['bug', 'triage']
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues found in e-mobility-charging-stations-simulator.
        Any misuse of this issue tracker will be closed immediately, such as simulator configuration support, simulator usage support, ...
        Support requests are expected to be filed in the [Discussions](https://github.com/poolifier/poolifier/discussions) Q&A category.

        Please fill in as much of the template below as you're able.
  - type: checkboxes
    attributes:
      label: Duplicate issue
      options:
        - label: I've searched for any related issues and avoided creating a duplicate issue.
          required: true
  - type: dropdown
    attributes:
      label: Component
      description: The component of the simulator that the bug is related to.
      options:
        - Simulator
        - Web UI
        - OCPP 2 Mock Server
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Description of the bug.
      placeholder: |
        - Please include error outputs in the 'Actual result' input field from 'pnpm start:dev', if any
    validations:
      required: true
  - type: input
    attributes:
      label: Version
    validations:
      required: true
  - type: input
    attributes:
      label: Node.js version
      description: Output of `node -v`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: System
      description: Output of `npx --yes envinfo --system`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected result
      description: What you expected to happen.
  - type: textarea
    attributes:
      label: Actual result
      description: What actually happened.
      placeholder: |
        - Please include the actual error outputs generated from 'pnpm start:dev', if any
        - Please include the actual error log messages, if any
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug.
  - type: textarea
    attributes:
      label: Attachments
      description: Logs, configurations, screenshots, screencast, etc.
