name: 'Feature request'
title: '[FEATURE] '
labels: ['enhancement', 'triage']
description: Request a feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for requesting a feature.

        This issue tracker is for feature requests in e-mobility-charging-stations-simulator.
        Any misuse of this issue tracker will be closed immediately, such as simulator configuration support, simulator usage support, ...
        Support requests are expected to be filed in the [Discussions](https://github.com/poolifier/poolifier/discussions) Q&A category.

        Please fill in as much of the template below as you're able.
  - type: checkboxes
    attributes:
      label: Duplicate issue
      options:
        - label: I've searched for any related issues and avoided creating a duplicate issue.
          required: true
  - type: dropdown
    attributes:
      label: Component
      description: The component of the simulator that the feature is related to.
      options:
        - Simulator
        - Web UI
        - OCPP 2 Mock Server
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature.
      placeholder: |
        - If your feature request is related to a problem, please describe it
        - If you have solutions in mind, please describe them
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Architecture or design documents, screenshots, screencast, etc.
